name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rocky-gcc-debug:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/hel-astro-lab/tyvi-rocky-gcc:latest

    steps:
      - uses: actions/checkout@v7

      - name: Configure
        run: |
          rocthrust_DIR=$ROCTHRUST_INSTALL_PREFIX/lib/cmake/rocthrust cmake \
          --preset unixlike-g++-debug \
          -DCMAKE_CXX_COMPILER=/opt/rh/gcc-toolset-14/root/usr/bin/g++ \
          -DMPI_HOME=/usr/lib64/openmpi/

      - name: Build
        run: make -j4 -C out/build/unixlike-g++-debug

      - name: Test
        run: ctest -j4 --test-dir out/build/unixlike-g++-debug --output-on-failure
